import {
  BarChart3,
  BookOpen,
  Bug,
  CalendarCheck,
  ClipboardCheck,
  ClipboardList,
  FileQuestion,
  FileText,
  GraduationCap,
  KeyRound,
  Library,
  ListChecks,
  Megaphone,
  MonitorSmartphone,
  PlayCircle,
  School,
  Search,
  Settings,
  ShieldCheck,
  TableProperties,
  UserCog,
  Users,
  UsersRound,
} from "lucide-react";

export type HelpGroup = "Documentation" | "FAQs" | "Videos" | "Release Notes";

export type HelpArticle = {
  slug: string;
  title: string;
  description: string;
  category: string;
  group: HelpGroup;
  roles: string[];
  module: string;
  icon: keyof typeof helpIcons;
  tags: string[];
  overview: string;
  prerequisites: string[];
  steps: string[];
  screenshots: string[];
  video: string;
  commonErrors: Array<{ title: string; answer: string }>;
  faqs: Array<{ question: string; answer: string }>;
  related: string[];
  permissions?: Array<{ action: string; roles: string[] }>;
};

export const helpIcons = {
  attendance: ClipboardCheck,
  assignments: ClipboardList,
  exams: GraduationCap,
  students: Users,
  teachers: UsersRound,
  reports: BarChart3,
  started: BookOpen,
  institution: School,
  timetable: CalendarCheck,
  roles: ShieldCheck,
  mobile: MonitorSmartphone,
  troubleshooting: Bug,
  release: Megaphone,
  faq: FileQuestion,
  video: PlayCircle,
  permission: KeyRound,
  import: TableProperties,
  export: FileText,
  user: UserCog,
  settings: Settings,
  search: Search,
  docs: Library,
  checklist: ListChecks,
};

export const quickTopics = ["Attendance", "Assignments", "Exams", "Students", "Teachers", "Reports"];

export const helpCategories = [
  { title: "Getting Started", slug: "getting-started", description: "First login, dashboard, and setup path.", icon: "started" },
  { title: "Institution Setup", slug: "institution-setup", description: "Create institutions, sessions, programs, and sections.", icon: "institution" },
  { title: "Attendance", slug: "attendance", description: "Setup, mark, edit, and report attendance.", icon: "attendance" },
  { title: "Assignment Management", slug: "assignments", description: "Create assignments, collect submissions, and grade work.", icon: "assignments" },
  { title: "Student Management", slug: "students", description: "Admissions, profiles, enrolment, promotions, and records.", icon: "students" },
  { title: "Teacher Management", slug: "teachers", description: "Teacher profiles, subject mapping, and class responsibilities.", icon: "teachers" },
  { title: "Timetable", slug: "timetable", description: "Slots, subject teachers, class teachers, and schedules.", icon: "timetable" },
  { title: "Exams & Results", slug: "exams-results", description: "Exam setup, marks entry, grading, and publishing results.", icon: "exams" },
  { title: "Reports & Analytics", slug: "reports", description: "Attendance, performance, assignment, and institution reports.", icon: "reports" },
  { title: "Roles & Permissions", slug: "roles-permissions", description: "Role access, institution overrides, and permission matrix.", icon: "roles" },
  { title: "Mobile App", slug: "mobile-app", description: "Student, parent, and staff mobile workflows.", icon: "mobile" },
  { title: "Troubleshooting", slug: "troubleshooting", description: "Fix common setup, access, and data issues.", icon: "troubleshooting" },
] as const;

export const roleDocs = [
  { title: "Super Admin", slug: "role-super-admin", description: "Platform setup, global content, and system controls.", icon: "roles" },
  { title: "Institution Admin", slug: "role-institution-admin", description: "Institution setup, users, academic data, and reports.", icon: "institution" },
  { title: "Principal", slug: "role-principal", description: "School overview, monitoring, attendance, and analytics.", icon: "reports" },
  { title: "Teacher", slug: "role-teacher", description: "Attendance, assignments, grading, and class reports.", icon: "teachers" },
  { title: "Student", slug: "role-student", description: "Assignments, attendance, results, and classroom access.", icon: "students" },
  { title: "Parent", slug: "role-parent", description: "Student progress, attendance, notifications, and fees.", icon: "user" },
  { title: "Accountant", slug: "role-accountant", description: "Fee workflows, receipts, dues, and financial reports.", icon: "settings" },
] as const;

export const popularArticles = [
  "Create your first institution",
  "Add students",
  "Create classes",
  "Mark attendance",
  "Create assignment",
  "Publish exam results",
];

export const recentUpdates = [
  { title: "Help Center command search with Ctrl+K", date: "17 Jun 2026" },
  { title: "Student classroom assignment submission flow", date: "16 Jun 2026" },
  { title: "Institution syllabus update workflow", date: "15 Jun 2026" },
  { title: "Assignment checking and marks visibility", date: "14 Jun 2026" },
];

const defaultPermissions = [
  { action: "View", roles: ["Institution Admin", "Principal", "Teacher"] },
  { action: "Create", roles: ["Institution Admin", "Teacher"] },
  { action: "Edit", roles: ["Institution Admin", "Teacher"] },
  { action: "Delete", roles: ["Institution Admin"] },
  { action: "Export", roles: ["Institution Admin", "Principal"] },
];

export const helpArticles: HelpArticle[] = [
  {
    slug: "attendance-setup",
    title: "Attendance Setup",
    description: "Prepare classes, students, timetable slots, and attendance marking.",
    category: "Attendance",
    group: "Documentation",
    roles: ["Institution Admin", "Principal", "Teacher"],
    module: "Attendance",
    icon: "attendance",
    tags: ["attendance", "setup", "classes", "timetable", "students"],
    overview: "Attendance setup prepares institution classes, sections, academic sessions, students, teachers, and timetable slots before attendance can be marked.",
    prerequisites: ["Institution created", "Academic session active", "Classes and sections created", "Students added and enrolled", "Class teacher or subject teacher mapped"],
    steps: ["Create the academic session.", "Create classes or programs.", "Attach sections and subjects.", "Assign class teachers.", "Create timetable slots.", "Add and enrol students.", "Start marking attendance from Manage Students > Attendance."],
    screenshots: ["Attendance setup checklist", "Timetable setup page", "Mark attendance screen"],
    video: "Attendance setup walkthrough",
    commonErrors: [
      { title: "Why can't I mark attendance?", answer: "Usually no timetable slot or active enrolment exists for the selected class, section, and date." },
      { title: "Students are missing from the list", answer: "Check student enrolment details: institution, class/program, section, and academic session must match." },
    ],
    faqs: [
      { question: "Can attendance be marked without timetable slots?", answer: "Full-day attendance can be simpler, but period-wise attendance requires timetable slots." },
      { question: "Who can mark attendance?", answer: "Institution admins and teachers with attendance permissions can mark attendance." },
    ],
    related: ["Institution Setup", "Student Management", "Timetable"],
    permissions: defaultPermissions,
  },
  {
    slug: "getting-started",
    title: "Getting Started",
    description: "Set up EduBird from first login to the first working academic workflow.",
    category: "Getting Started",
    group: "Documentation",
    roles: ["Super Admin", "Institution Admin", "Principal"],
    module: "Setup",
    icon: "started",
    tags: ["start", "onboarding", "dashboard", "setup"],
    overview: "Use this path when a new institution is starting EduBird from scratch.",
    prerequisites: ["Admin account created", "Institution details available", "Academic year information ready"],
    steps: ["Login to the admin panel.", "Create or select the institution.", "Create the academic session.", "Add programs, classes, sections, and subjects.", "Add staff and students.", "Configure attendance, assignments, and exams."],
    screenshots: ["Admin dashboard", "Institution form", "Academic setup screens"],
    video: "New institution onboarding",
    commonErrors: [{ title: "Setup page looks empty", answer: "Confirm your role has institution access and the correct institution is selected." }],
    faqs: [{ question: "What should be configured first?", answer: "Institution, academic year, classes, sections, then users and students." }],
    related: ["Institution Setup", "Roles & Permissions", "Student Management"],
    permissions: defaultPermissions,
  },
  {
    slug: "institution-setup",
    title: "Institution Setup",
    description: "Create school profile, academic sessions, classes, programs, sections, and subjects.",
    category: "Institution Setup",
    group: "Documentation",
    roles: ["Super Admin", "Institution Admin"],
    module: "Institutions",
    icon: "institution",
    tags: ["institution", "school", "program", "section", "academic year"],
    overview: "Institution setup creates the structure used by students, teachers, attendance, timetable, assignments, and reports.",
    prerequisites: ["Institution name and contact details", "Program or class list", "Academic session dates"],
    steps: ["Create the institution profile.", "Add academic years.", "Create programs or classes.", "Add sections.", "Attach subjects.", "Review the setup before enrolling students."],
    screenshots: ["Institution profile", "Programs", "Academic years"],
    video: "Institution setup walkthrough",
    commonErrors: [{ title: "Class is not visible in other modules", answer: "Check that the class/program belongs to the selected institution and academic session." }],
    faqs: [{ question: "Can one institution have multiple academic years?", answer: "Yes, keep only the current session active for daily operations." }],
    related: ["Getting Started", "Student Management", "Timetable"],
    permissions: defaultPermissions,
  },
  {
    slug: "assignments",
    title: "Assignment Management",
    description: "Create assignments, target classes or students, collect submissions, and grade answers.",
    category: "Assignments",
    group: "Documentation",
    roles: ["Institution Admin", "Teacher", "Student"],
    module: "Assignments",
    icon: "assignments",
    tags: ["assignment", "homework", "questions", "grading", "submission"],
    overview: "Assignments let staff publish objective or subjective homework to institutions, classes, sections, or specific students.",
    prerequisites: ["Students enrolled", "Assignment permission enabled", "Class, section, or student target selected"],
    steps: ["Create assignment details.", "Select assignment targets.", "Add objective or subjective questions.", "Publish the assignment.", "Students submit from Classroom.", "Teacher checks answers and marks as checked."],
    screenshots: ["Assignment list", "Question editor", "Student submission sheet"],
    video: "Create and grade assignments",
    commonErrors: [{ title: "Student cannot see assignment", answer: "Confirm the assignment target matches the student's institution, class, section, or student id." }],
    faqs: [{ question: "Can an assignment target one student?", answer: "Yes, select a specific student target after selecting institution, class, and section." }],
    related: ["Student Management", "Teacher Management", "Roles & Permissions"],
    permissions: defaultPermissions,
  },
  {
    slug: "students",
    title: "Student Management",
    description: "Add students, manage profiles, enrolment, cards, parents, and academic records.",
    category: "Students",
    group: "Documentation",
    roles: ["Institution Admin", "Principal", "Teacher"],
    module: "Students",
    icon: "students",
    tags: ["student", "enrolment", "profile", "parents", "records"],
    overview: "Student management stores student identity, enrolment, family, academic, and classroom access details.",
    prerequisites: ["Institution setup complete", "Classes and sections created", "Academic session active"],
    steps: ["Create a student profile.", "Fill profile and background details.", "Select institution, class, section, and session.", "Add parent details.", "Save and verify classroom access."],
    screenshots: ["Student form", "Enrolment step", "Student table"],
    video: "Add and enrol students",
    commonErrors: [{ title: "Student login shows no classroom data", answer: "Check student enrolment and classroom permissions for the student role." }],
    faqs: [{ question: "Can students be moved to another section?", answer: "Yes, edit the profile enrolment details and save the new section." }],
    related: ["Attendance Setup", "Assignments", "Roles & Permissions"],
    permissions: defaultPermissions,
  },
  {
    slug: "teachers",
    title: "Teacher Management",
    description: "Manage teacher profiles, subject mapping, class responsibilities, and module access.",
    category: "Teachers",
    group: "Documentation",
    roles: ["Institution Admin", "Principal", "Teacher"],
    module: "Teachers",
    icon: "teachers",
    tags: ["teacher", "subject", "class teacher", "permissions"],
    overview: "Teacher management connects staff profiles with subjects, timetable slots, class teacher ownership, and access permissions.",
    prerequisites: ["Teacher user account", "Subjects created", "Classes and sections available"],
    steps: ["Create or update teacher user.", "Assign institution membership.", "Map class teacher or subject teacher.", "Grant teacher permissions.", "Verify dashboard access."],
    screenshots: ["Teacher user profile", "Subject teacher mapping", "Role permissions"],
    video: "Teacher setup walkthrough",
    commonErrors: [{ title: "Teacher cannot mark attendance", answer: "Check teacher permissions and timetable/class teacher mapping." }],
    faqs: [{ question: "Can a teacher handle multiple subjects?", answer: "Yes, map the teacher to each subject and class as needed." }],
    related: ["Timetable", "Attendance Setup", "Assignments"],
    permissions: defaultPermissions,
  },
  {
    slug: "timetable",
    title: "Timetable",
    description: "Create slots, assign teachers, and prepare class schedules.",
    category: "Timetable",
    group: "Documentation",
    roles: ["Institution Admin", "Principal", "Teacher"],
    module: "Timetable",
    icon: "timetable",
    tags: ["timetable", "slots", "period", "subject teacher", "class teacher"],
    overview: "Timetable setup powers period-wise attendance and teacher schedules.",
    prerequisites: ["Subjects created", "Teachers added", "Classes and sections ready"],
    steps: ["Create timetable slots.", "Map subject teachers.", "Map class teachers.", "Add entries for class periods.", "Review conflicts before use."],
    screenshots: ["Timetable slots", "Subject teacher mapping", "Class teacher mapping"],
    video: "Timetable setup guide",
    commonErrors: [{ title: "Period attendance has no periods", answer: "Create timetable slots and entries for the selected class and date." }],
    faqs: [{ question: "Can slots be reused?", answer: "Yes, slots can be shared across timetable entries." }],
    related: ["Attendance Setup", "Teacher Management", "Institution Setup"],
    permissions: defaultPermissions,
  },
  {
    slug: "exams-results",
    title: "Exams & Results",
    description: "Create exams, enter marks, calculate grades, and publish results.",
    category: "Exams & Results",
    group: "Documentation",
    roles: ["Institution Admin", "Principal", "Teacher", "Student", "Parent"],
    module: "Exams",
    icon: "exams",
    tags: ["exam", "result", "marks", "grade", "publish"],
    overview: "Exam and result workflows manage assessments from setup to published student reports.",
    prerequisites: ["Classes and subjects ready", "Students enrolled", "Exam permission enabled"],
    steps: ["Create exam details.", "Attach class and subjects.", "Enter marks.", "Review grading.", "Publish results.", "Students and parents view results."],
    screenshots: ["Exam list", "Marks entry", "Result sheet"],
    video: "Publish exam results",
    commonErrors: [{ title: "Result is not visible to students", answer: "Check whether the result has been published and student has result permission." }],
    faqs: [{ question: "Can marks be edited after publish?", answer: "Only users with edit permission should update published marks." }],
    related: ["Students", "Reports", "Roles & Permissions"],
    permissions: defaultPermissions,
  },
  {
    slug: "reports",
    title: "Reports & Analytics",
    description: "Generate attendance, assignment, performance, and institution reports.",
    category: "Reports",
    group: "Documentation",
    roles: ["Institution Admin", "Principal", "Teacher"],
    module: "Reports",
    icon: "reports",
    tags: ["reports", "analytics", "export", "performance"],
    overview: "Reports give institution teams a quick view of attendance, performance, assignments, and student progress.",
    prerequisites: ["Operational data available", "Report permission enabled"],
    steps: ["Open the report module.", "Select institution and filters.", "Review summary cards.", "Open drill-down details.", "Export if needed."],
    screenshots: ["Report dashboard", "Attendance report", "Performance report"],
    video: "Reports overview",
    commonErrors: [{ title: "Report shows zero data", answer: "Check selected date range, institution, class, and section filters." }],
    faqs: [{ question: "Can reports be exported?", answer: "Export support depends on the module and permission granted." }],
    related: ["Attendance", "Assignments", "Exams & Results"],
    permissions: defaultPermissions,
  },
  {
    slug: "roles-permissions",
    title: "Roles & Permissions",
    description: "Control module access with platform permissions and institution overrides.",
    category: "Roles & Permissions",
    group: "Documentation",
    roles: ["Super Admin", "Institution Admin"],
    module: "Access Control",
    icon: "roles",
    tags: ["role", "permission", "override", "access", "scope"],
    overview: "Permissions decide which modules and actions users can access, with institution overrides for local control.",
    prerequisites: ["Roles created", "Permissions synced", "Institution memberships configured"],
    steps: ["Review available permissions.", "Assign default role permissions.", "Add institution memberships.", "Use institution role permissions for overrides.", "Test with the target role."],
    screenshots: ["Role permissions", "Institution overrides", "Permission selector"],
    video: "Permission management walkthrough",
    commonErrors: [{ title: "Admin cannot override permissions", answer: "They need institution role permission create/edit access for their institution scope." }],
    faqs: [{ question: "Can institution admins override platform defaults?", answer: "Yes, only for institution-scoped permissions they are allowed to manage." }],
    related: ["User Management", "Institution Setup", "Permission Matrix"],
    permissions: [
      { action: "View Permissions", roles: ["Super Admin", "Institution Admin"] },
      { action: "Create Overrides", roles: ["Institution Admin"] },
      { action: "Edit Overrides", roles: ["Institution Admin"] },
      { action: "Delete Overrides", roles: ["Institution Admin"] },
    ],
  },
  {
    slug: "mobile-app",
    title: "Mobile App Guide",
    description: "Student, parent, and staff mobile workflows.",
    category: "Mobile App",
    group: "Documentation",
    roles: ["Student", "Parent", "Teacher"],
    module: "Mobile App",
    icon: "mobile",
    tags: ["mobile", "app", "student", "parent"],
    overview: "The mobile app gives students, parents, and teachers quick access to classroom updates.",
    prerequisites: ["Active user account", "Correct role and permissions", "Institution membership or student enrolment"],
    steps: ["Install the mobile app.", "Login with your account.", "Open dashboard.", "Use role-specific modules.", "Enable notifications."],
    screenshots: ["Mobile login", "Student classroom", "Parent overview"],
    video: "Mobile app tour",
    commonErrors: [{ title: "Login works but no data appears", answer: "Check role assignment, institution membership, and student enrolment." }],
    faqs: [{ question: "Can parents view multiple students?", answer: "Yes, when parent-student links are configured." }],
    related: ["Student Management", "Roles & Permissions", "Troubleshooting"],
  },
  {
    slug: "troubleshooting",
    title: "Troubleshooting Center",
    description: "Fix common setup, permission, import, and module issues.",
    category: "Troubleshooting",
    group: "FAQs",
    roles: ["Super Admin", "Institution Admin", "Principal", "Teacher", "Student", "Parent"],
    module: "Support",
    icon: "troubleshooting",
    tags: ["error", "fix", "issue", "support", "faq"],
    overview: "Troubleshooting collects common issues and the quickest checks to resolve them.",
    prerequisites: ["Know the affected role", "Know the institution, class, section, or module involved"],
    steps: ["Check user role.", "Check permission.", "Check institution scope.", "Check required setup data.", "Retry the workflow.", "Contact support if the issue continues."],
    screenshots: ["Permission selector", "Student enrolment", "Support ticket"],
    video: "Troubleshooting basics",
    commonErrors: [
      { title: "403 permission error", answer: "Grant the required permission or institution role override for that module action." },
      { title: "Data not loading", answer: "Confirm institution, class, section, session, and date filters." },
    ],
    faqs: [{ question: "Where should admins start debugging?", answer: "Start with role, permission, institution membership, and required setup data." }],
    related: ["Roles & Permissions", "Getting Started", "Institution Setup"],
  },
  {
    slug: "release-notes",
    title: "Release Notes",
    description: "Latest product changes, improvements, and fixes.",
    category: "Release Notes",
    group: "Release Notes",
    roles: ["Super Admin", "Institution Admin", "Principal", "Teacher"],
    module: "Updates",
    icon: "release",
    tags: ["release", "updates", "changes"],
    overview: "Release notes summarize important EduBird changes.",
    prerequisites: ["None"],
    steps: recentUpdates.map((update) => `${update.date}: ${update.title}`),
    screenshots: ["Recent updates list"],
    video: "Product update summary",
    commonErrors: [],
    faqs: [{ question: "How often are release notes updated?", answer: "They should be updated whenever a visible feature or workflow changes." }],
    related: ["Getting Started", "Troubleshooting"],
  },
  {
    slug: "permission-matrix",
    title: "Permission Matrix",
    description: "Understand view, create, edit, delete, and export permissions by role.",
    category: "Roles & Permissions",
    group: "Documentation",
    roles: ["Super Admin", "Institution Admin"],
    module: "Access Control",
    icon: "permission",
    tags: ["permission", "matrix", "roles", "scope"],
    overview: "The permission matrix explains which roles can perform common module actions.",
    prerequisites: ["Roles configured", "Permissions synced"],
    steps: ["Choose a module.", "Review view/create/edit/delete/export actions.", "Compare role access.", "Apply overrides if required.", "Test from the target user account."],
    screenshots: ["Permission matrix", "Role permissions"],
    video: "Permission matrix guide",
    commonErrors: [{ title: "Permission exists but page is hidden", answer: "Some pages also have role visibility rules, such as Classroom being student-only." }],
    faqs: [{ question: "Are all permissions institution scoped?", answer: "No. Some permissions are platform scoped and managed only at platform level." }],
    related: ["Roles & Permissions", "User Management"],
    permissions: defaultPermissions,
  },
  {
    slug: "user-management",
    title: "User Management",
    description: "Create users, assign roles, reset access, and manage institution memberships.",
    category: "User Management",
    group: "Documentation",
    roles: ["Super Admin", "Institution Admin"],
    module: "Users",
    icon: "user",
    tags: ["users", "roles", "membership", "login"],
    overview: "User management controls account identity, role assignment, and institution membership.",
    prerequisites: ["Role list available", "Institution selected for institution roles"],
    steps: ["Create user account.", "Assign platform or institution role.", "Attach institution membership when needed.", "Save profile details.", "Verify login and permissions."],
    screenshots: ["User form", "Institution membership", "Role selector"],
    video: "User management basics",
    commonErrors: [{ title: "Institution role cannot be saved", answer: "Select an institution before saving an institution-scoped role." }],
    faqs: [{ question: "Can one user have multiple roles?", answer: "Yes, depending on platform and institution membership configuration." }],
    related: ["Roles & Permissions", "Institution Setup"],
    permissions: defaultPermissions,
  },
  {
    slug: "data-import",
    title: "Data Import Guide",
    description: "Prepare bulk data imports for students, attendance, and academic records.",
    category: "Data",
    group: "Documentation",
    roles: ["Institution Admin"],
    module: "Imports",
    icon: "import",
    tags: ["import", "excel", "bulk", "data"],
    overview: "Data imports help institutions add records faster when onboarding or migrating.",
    prerequisites: ["Clean spreadsheet", "Matching institution/class/section names", "Import permission enabled"],
    steps: ["Download or follow the template.", "Fill required columns.", "Validate class and section names.", "Upload the file.", "Review errors and retry failed rows."],
    screenshots: ["Import template", "Upload screen", "Validation results"],
    video: "Bulk import walkthrough",
    commonErrors: [{ title: "Rows failed validation", answer: "Check required columns, duplicate records, and mismatched class or section names." }],
    faqs: [{ question: "Can failed rows be retried?", answer: "Yes, correct the file and upload again." }],
    related: ["Student Management", "Attendance Setup"],
  },
  {
    slug: "data-export",
    title: "Data Export Guide",
    description: "Export reports, student data, attendance, and results.",
    category: "Data",
    group: "Documentation",
    roles: ["Institution Admin", "Principal"],
    module: "Exports",
    icon: "export",
    tags: ["export", "report", "download", "data"],
    overview: "Exports provide offline copies of operational records and reports.",
    prerequisites: ["Data available", "Export permission enabled"],
    steps: ["Open the target module.", "Apply filters.", "Review visible records.", "Click export when available.", "Store downloaded files securely."],
    screenshots: ["Report filters", "Export button"],
    video: "Exporting reports",
    commonErrors: [{ title: "Export button is hidden", answer: "Check export permission for the module and role." }],
    faqs: [{ question: "Can students export data?", answer: "Student export access depends on module-specific permission policy." }],
    related: ["Reports", "Permission Matrix"],
  },
  {
    slug: "api-documentation",
    title: "API Documentation",
    description: "Developer reference for integrations and mobile clients.",
    category: "API Documentation",
    group: "Documentation",
    roles: ["Super Admin"],
    module: "API",
    icon: "docs",
    tags: ["api", "developer", "integration", "mobile"],
    overview: "API documentation explains authentication, permissions, endpoints, and integration expectations.",
    prerequisites: ["Developer access", "API base URL", "Test user credentials"],
    steps: ["Review authentication.", "Check permission model.", "Call lookup APIs.", "Use admin endpoints with access token.", "Handle errors consistently."],
    screenshots: ["API reference", "Auth response"],
    video: "API overview",
    commonErrors: [{ title: "API returns 403", answer: "The access token is valid but missing the required permission." }],
    faqs: [{ question: "Can public APIs be used without login?", answer: "Only public lookup APIs should be unauthenticated." }],
    related: ["Roles & Permissions", "Mobile App Guide"],
  },
  {
    slug: "system-requirements",
    title: "System Requirements",
    description: "Recommended browser, device, and network requirements.",
    category: "System Requirements",
    group: "Documentation",
    roles: ["Super Admin", "Institution Admin", "Teacher", "Student", "Parent"],
    module: "System",
    icon: "settings",
    tags: ["system", "browser", "device", "network"],
    overview: "System requirements help users run EduBird smoothly across admin and mobile workflows.",
    prerequisites: ["Modern browser", "Stable internet connection"],
    steps: ["Use latest Chrome, Edge, or Safari.", "Enable JavaScript.", "Allow popups/downloads for exports.", "Use stable internet for uploads.", "Keep mobile app updated."],
    screenshots: ["Browser support", "Mobile app update"],
    video: "System readiness checklist",
    commonErrors: [{ title: "Upload fails on slow network", answer: "Retry on a stable connection and reduce file size if needed." }],
    faqs: [{ question: "Does EduBird work on mobile browser?", answer: "Most pages work, but app-first workflows are better in the mobile app." }],
    related: ["Mobile App Guide", "Troubleshooting"],
  },
];

export function getArticle(slug: string) {
  return helpArticles.find((article) => article.slug === slug);
}

export function getCategory(slug: string) {
  return helpCategories.find((category) => category.slug === slug);
}

export function getRoleDoc(slug: string) {
  return roleDocs.find((role) => role.slug === slug);
}

export function getHelpEntry(slug: string) {
  return getArticle(slug) ?? getCategory(slug) ?? getRoleDoc(slug);
}

export function getArticlesForCategory(categoryTitle: string) {
  return helpArticles.filter((article) => article.category === categoryTitle || article.module === categoryTitle);
}

export function getArticlesForRole(roleTitle: string) {
  return helpArticles.filter((article) => article.roles.includes(roleTitle));
}

export function getSearchEntries() {
  return [
    { title: "Help Center", description: "Browse all EduBird help guides.", href: "/help", group: "Documentation" as HelpGroup, icon: "search" as const, keywords: "home help docs documentation" },
    ...helpCategories.map((category) => ({
      title: category.title,
      description: category.description,
      href: `/help/${category.slug}`,
      group: "Documentation" as HelpGroup,
      icon: category.icon,
      keywords: category.title,
    })),
    ...roleDocs.map((role) => ({
      title: `${role.title} Docs`,
      description: role.description,
      href: `/help/${role.slug}`,
      group: "Documentation" as HelpGroup,
      icon: role.icon,
      keywords: role.title,
    })),
    ...helpArticles.map((article) => ({
      title: article.title,
      description: article.description,
      href: article.slug === "attendance-setup" ? "/help/attendance-setup" : `/help/${article.slug}`,
      group: article.group,
      icon: article.icon,
      keywords: [...article.tags, article.module, ...article.roles].join(" "),
    })),
    ...helpArticles.flatMap((article) =>
      article.faqs.map((faq) => ({
        title: faq.question,
        description: faq.answer,
        href: `/help/${article.slug}#faqs`,
        group: "FAQs" as HelpGroup,
        icon: "faq" as const,
        keywords: `${article.title} ${article.tags.join(" ")}`,
      }))
    ),
    ...helpArticles.map((article) => ({
      title: article.video,
      description: `Video tutorial for ${article.title}.`,
      href: `/help/${article.slug}#video`,
      group: "Videos" as HelpGroup,
      icon: "video" as const,
      keywords: `${article.title} video tutorial`,
    })),
    ...recentUpdates.map((update) => ({
      title: update.title,
      description: update.date,
      href: "/help/release-notes",
      group: "Release Notes" as HelpGroup,
      icon: "release" as const,
      keywords: "release update changes",
    })),
  ];
}
