export type PublicInstitute = {
  id: number;
  name: string;
  location: string;
  locationKey: string;
  type: string;
  course: string;
  courses: number;
  rating: number;
  reviews: number;
  students: string;
  image: string;
  category: string;
  verified: boolean;
  established: number;
  filters: string[];
};

export type FilterSection = {
  title: string;
  options: FilterOption[];
};

export type FilterOption = {
  label: string;
  value: string;
};

const campusImages = [
  "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1606761568499-6d2451b23c66?auto=format&fit=crop&w=900&q=80",
];

export const institutes: PublicInstitute[] = [
  {
    id: 1,
    name: "Tech Academy Pro",
    location: "New Delhi, India",
    locationKey: "delhi",
    type: "training",
    course: "data-science",
    courses: 120,
    rating: 4.8,
    reviews: 512,
    students: "12K+",
    image: campusImages[0],
    category: "Data Science",
    verified: true,
    established: 2019,
    filters: ["aicte", "private", "on-campus", "fee-1l-3l", "placement-cell", "job-assistance", "open-now"],
  },
  {
    id: 2,
    name: "Global Institute",
    location: "Bangalore, India",
    locationKey: "bangalore",
    type: "university",
    course: "engineering",
    courses: 95,
    rating: 4.7,
    reviews: 398,
    students: "8K+",
    image: campusImages[1],
    category: "Engineering",
    verified: true,
    established: 2016,
    filters: ["ugc", "private", "hybrid", "fee-above-3l", "hostel", "library", "entrance-required"],
  },
  {
    id: 3,
    name: "Marketing Hub",
    location: "Mumbai, India",
    locationKey: "mumbai",
    type: "coaching",
    course: "marketing",
    courses: 60,
    rating: 4.9,
    reviews: 641,
    students: "15K+",
    image: campusImages[2],
    category: "Digital Marketing",
    verified: true,
    established: 2020,
    filters: ["iso", "private", "online", "fee-under-50k", "portfolio-review", "direct-admission"],
  },
  {
    id: 4,
    name: "Design School Plus",
    location: "Pune, India",
    locationKey: "pune",
    type: "college",
    course: "design",
    courses: 75,
    rating: 4.6,
    reviews: 278,
    students: "6K+",
    image: campusImages[3],
    category: "Design",
    verified: true,
    established: 2018,
    filters: ["naac", "autonomous", "on-campus", "fee-50k-1l", "labs", "portfolio-review", "open-now"],
  },
  {
    id: 5,
    name: "Cloud Masters",
    location: "Hyderabad, India",
    locationKey: "hyderabad",
    type: "training",
    course: "engineering",
    courses: 70,
    rating: 4.8,
    reviews: 331,
    students: "9K+",
    image: campusImages[4],
    category: "Engineering",
    verified: true,
    established: 2021,
    filters: ["iso", "private", "hybrid", "fee-1l-3l", "labs", "internship", "counselling"],
  },
  {
    id: 6,
    name: "Business Institute",
    location: "Kolkata, India",
    locationKey: "kolkata",
    type: "college",
    course: "management",
    courses: 55,
    rating: 4.7,
    reviews: 266,
    students: "7K+",
    image: campusImages[5],
    category: "Management",
    verified: true,
    established: 2015,
    filters: ["ugc", "government", "on-campus", "fee-50k-1l", "library", "hiring-partners", "direct-admission"],
  },
  {
    id: 7,
    name: "NextGen Engineering College",
    location: "New Delhi, India",
    locationKey: "delhi",
    type: "college",
    course: "engineering",
    courses: 84,
    rating: 4.5,
    reviews: 221,
    students: "6.5K+",
    image: campusImages[0],
    category: "Engineering",
    verified: true,
    established: 2017,
    filters: ["aicte", "private", "on-campus", "fee-1l-3l", "labs", "placement-cell"],
  },
  {
    id: 8,
    name: "Metro Management School",
    location: "Mumbai, India",
    locationKey: "mumbai",
    type: "college",
    course: "management",
    courses: 48,
    rating: 4.4,
    reviews: 186,
    students: "5K+",
    image: campusImages[1],
    category: "Management",
    verified: true,
    established: 2014,
    filters: ["ugc", "private", "hybrid", "fee-50k-1l", "hiring-partners"],
  },
  {
    id: 9,
    name: "Pixel Design Academy",
    location: "Bangalore, India",
    locationKey: "bangalore",
    type: "training",
    course: "design",
    courses: 38,
    rating: 4.6,
    reviews: 305,
    students: "4K+",
    image: campusImages[2],
    category: "Design",
    verified: true,
    established: 2022,
    filters: ["iso", "private", "online", "fee-under-50k", "portfolio-review"],
  },
  {
    id: 10,
    name: "SkillBridge Institute",
    location: "Pune, India",
    locationKey: "pune",
    type: "training",
    course: "data-science",
    courses: 66,
    rating: 4.3,
    reviews: 174,
    students: "4.8K+",
    image: campusImages[3],
    category: "Data Science",
    verified: true,
    established: 2019,
    filters: ["iso", "private", "hybrid", "fee-50k-1l", "job-assistance"],
  },
  {
    id: 11,
    name: "BrightPath University",
    location: "Hyderabad, India",
    locationKey: "hyderabad",
    type: "university",
    course: "management",
    courses: 102,
    rating: 4.7,
    reviews: 429,
    students: "11K+",
    image: campusImages[4],
    category: "Management",
    verified: true,
    established: 2013,
    filters: ["ugc", "private", "on-campus", "fee-above-3l", "hostel", "library"],
  },
  {
    id: 12,
    name: "AdCraft Marketing School",
    location: "Kolkata, India",
    locationKey: "kolkata",
    type: "coaching",
    course: "marketing",
    courses: 34,
    rating: 4.2,
    reviews: 145,
    students: "3.2K+",
    image: campusImages[5],
    category: "Digital Marketing",
    verified: true,
    established: 2020,
    filters: ["iso", "private", "online", "fee-under-50k", "direct-admission"],
  },
  {
    id: 13,
    name: "Apex Cloud Campus",
    location: "Bangalore, India",
    locationKey: "bangalore",
    type: "training",
    course: "engineering",
    courses: 58,
    rating: 4.8,
    reviews: 376,
    students: "7.4K+",
    image: campusImages[0],
    category: "Engineering",
    verified: true,
    established: 2021,
    filters: ["aicte", "private", "hybrid", "fee-1l-3l", "labs", "internship"],
  },
  {
    id: 14,
    name: "Northstar Data Institute",
    location: "New Delhi, India",
    locationKey: "delhi",
    type: "university",
    course: "data-science",
    courses: 73,
    rating: 4.6,
    reviews: 282,
    students: "8.1K+",
    image: campusImages[1],
    category: "Data Science",
    verified: true,
    established: 2018,
    filters: ["ugc", "private", "on-campus", "fee-1l-3l", "library", "placement-cell"],
  },
  {
    id: 15,
    name: "Urban Business College",
    location: "Mumbai, India",
    locationKey: "mumbai",
    type: "college",
    course: "management",
    courses: 52,
    rating: 4.1,
    reviews: 119,
    students: "4.1K+",
    image: campusImages[2],
    category: "Management",
    verified: true,
    established: 2016,
    filters: ["naac", "autonomous", "on-campus", "fee-50k-1l", "hiring-partners"],
  },
  {
    id: 16,
    name: "Creative Minds Studio",
    location: "Pune, India",
    locationKey: "pune",
    type: "coaching",
    course: "design",
    courses: 29,
    rating: 4.5,
    reviews: 197,
    students: "2.8K+",
    image: campusImages[3],
    category: "Design",
    verified: true,
    established: 2022,
    filters: ["iso", "private", "weekend", "fee-under-50k", "portfolio-review"],
  },
  {
    id: 17,
    name: "Digital Growth Hub",
    location: "Hyderabad, India",
    locationKey: "hyderabad",
    type: "training",
    course: "marketing",
    courses: 45,
    rating: 4.4,
    reviews: 239,
    students: "5.6K+",
    image: campusImages[4],
    category: "Digital Marketing",
    verified: true,
    established: 2019,
    filters: ["iso", "private", "online", "fee-50k-1l", "job-assistance"],
  },
  {
    id: 18,
    name: "Eastern Tech University",
    location: "Kolkata, India",
    locationKey: "kolkata",
    type: "university",
    course: "engineering",
    courses: 118,
    rating: 4.6,
    reviews: 344,
    students: "10K+",
    image: campusImages[5],
    category: "Engineering",
    verified: true,
    established: 2012,
    filters: ["ugc", "government", "on-campus", "fee-1l-3l", "hostel", "labs"],
  },
  {
    id: 19,
    name: "Insight Analytics Pro",
    location: "Mumbai, India",
    locationKey: "mumbai",
    type: "training",
    course: "data-science",
    courses: 42,
    rating: 4.9,
    reviews: 418,
    students: "6.2K+",
    image: campusImages[0],
    category: "Data Science",
    verified: true,
    established: 2023,
    filters: ["iso", "private", "hybrid", "fee-1l-3l", "internship", "job-assistance"],
  },
  {
    id: 20,
    name: "DesignVerse University",
    location: "New Delhi, India",
    locationKey: "delhi",
    type: "university",
    course: "design",
    courses: 64,
    rating: 4.3,
    reviews: 165,
    students: "5.1K+",
    image: campusImages[1],
    category: "Design",
    verified: true,
    established: 2017,
    filters: ["ugc", "private", "on-campus", "fee-above-3l", "library", "portfolio-review"],
  },
];

export const locationOptions: FilterOption[] = [
  { label: "All Locations", value: "all" },
  { label: "Delhi", value: "delhi" },
  { label: "Mumbai", value: "mumbai" },
  { label: "Bangalore", value: "bangalore" },
  { label: "Pune", value: "pune" },
  { label: "Hyderabad", value: "hyderabad" },
  { label: "Kolkata", value: "kolkata" },
];

export const typeOptions: FilterOption[] = [
  { label: "All Types", value: "all" },
  { label: "College", value: "college" },
  { label: "University", value: "university" },
  { label: "Training Institute", value: "training" },
  { label: "Coaching Center", value: "coaching" },
];

export const courseOptions: FilterOption[] = [
  { label: "All Courses", value: "all" },
  { label: "Engineering", value: "engineering" },
  { label: "Management", value: "management" },
  { label: "Data Science", value: "data-science" },
  { label: "Design", value: "design" },
  { label: "Digital Marketing", value: "marketing" },
];

export const ratingOptions: FilterOption[] = [
  { label: "Any Rating", value: "0" },
  { label: "Rating: 4.0+", value: "4" },
  { label: "Rating: 4.5+", value: "4.5" },
  { label: "Rating: 4.8+", value: "4.8" },
];

export const sortOptions: FilterOption[] = [
  { label: "Popular", value: "popular" },
  { label: "Highest Rated", value: "rating-desc" },
  { label: "Most Students", value: "students-desc" },
  { label: "Newest", value: "newest" },
];

export const moreFilterSections: FilterSection[] = [
  {
    title: "Accreditation",
    options: [
      { label: "AICTE Approved", value: "aicte" },
      { label: "UGC Recognized", value: "ugc" },
      { label: "NAAC A+", value: "naac" },
      { label: "ISO Certified", value: "iso" },
    ],
  },
  {
    title: "Ownership",
    options: [
      { label: "Private", value: "private" },
      { label: "Government", value: "government" },
      { label: "Deemed University", value: "deemed" },
      { label: "Autonomous", value: "autonomous" },
    ],
  },
  {
    title: "Learning Mode",
    options: [
      { label: "On Campus", value: "on-campus" },
      { label: "Online", value: "online" },
      { label: "Hybrid", value: "hybrid" },
      { label: "Weekend Batch", value: "weekend" },
    ],
  },
  {
    title: "Fee Range",
    options: [
      { label: "Under Rs. 50K", value: "fee-under-50k" },
      { label: "Rs. 50K - Rs. 1L", value: "fee-50k-1l" },
      { label: "Rs. 1L - Rs. 3L", value: "fee-1l-3l" },
      { label: "Above Rs. 3L", value: "fee-above-3l" },
    ],
  },
  {
    title: "Facilities",
    options: [
      { label: "Hostel", value: "hostel" },
      { label: "Placement Cell", value: "placement-cell" },
      { label: "Library", value: "library" },
      { label: "Labs", value: "labs" },
      { label: "Transport", value: "transport" },
      { label: "Scholarships", value: "scholarships" },
    ],
  },
  {
    title: "Placement Support",
    options: [
      { label: "Internship Included", value: "internship" },
      { label: "Job Assistance", value: "job-assistance" },
      { label: "Hiring Partners", value: "hiring-partners" },
      { label: "Portfolio Review", value: "portfolio-review" },
    ],
  },
  {
    title: "Admission Status",
    options: [
      { label: "Open Now", value: "open-now" },
      { label: "Entrance Required", value: "entrance-required" },
      { label: "Direct Admission", value: "direct-admission" },
      { label: "Counselling Available", value: "counselling" },
    ],
  },
];
