"use client";

import { useState, useEffect } from "react";
import {
  FileText,
  Building2,
  GraduationCap,
  Share2,
  Printer,
  Copy,
  Check,
  Download,
  ShieldCheck,
  CheckCircle2,
  Calendar,
  Lock,
  ExternalLink,
  Award,
  BadgeCheck,
  AlertCircle,
  FileCheck2,
  Percent,
  IndianRupee,
  Save,
  RotateCcw,
  Edit3,
  Eye,
  Sliders,
  Sparkles,
  Loader2,
  Scale,
  Users,
} from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { InstitutionProfile } from "@/lib/types/institution";

interface InstitutionAgreementDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  institution: InstitutionProfile | null;
}

export function InstitutionAgreementDialog({
  open,
  onOpenChange,
  institution,
}: InstitutionAgreementDialogProps) {
  const [copiedTab, setCopiedTab] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState("edubird-org");
  const [isEditing, setIsEditing] = useState(false);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);

  // Platform Commercial Rates
  const [platformSalePercentage, setPlatformSalePercentage] = useState("10.00");
  const [enquiryCommission, setEnquiryCommission] = useState("50.00");
  const [affiliateCommissionPercentage, setAffiliateCommissionPercentage] = useState("10.00");

  // Custom Editable Terms
  const [orgTerms, setOrgTerms] = useState("");
  const [studentTerms, setStudentTerms] = useState("");
  const [affiliateTerms, setAffiliateTerms] = useState("");

  const orgName = institution?.name || "Partner Organization";
  const orgType = institution?.type_name || "Educational Institution";
  const orgCity = (institution as any)?.city || (institution as any)?.address || "Headquarters";
  const orgEmail = institution?.email || "official@institution.edu";
  const orgPhone = institution?.phone || "+91 98765 43210";
  const agreementDate = new Date().toLocaleDateString("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
  const agreementRef = "EDUBIRD-AGR-" + (institution?.id || "001") + "-" + new Date().getFullYear();

  // Standard Default Templates Generator
  const getDefaultOrgTerms = (salePct: string, enqComm: string) => 
    "1. APPOINTMENT & SCOPE OF PARTNERSHIP\n" +
    "The Institution hereby partners with EduBird Platform as an authorized digital admissions, course publication, and academic discovery partner. EduBird shall provide cloud-based course listings, lead management, verified student applications, and payment collection gateway services.\n\n" +
    "2. COMMERCIAL TERMS & PLATFORM REVENUE SHARE\n" +
    "- Course Sale Commission: EduBird Platform shall receive a platform revenue share of " + salePct + "% on every course admission, program enrollment, or tuition fee collected through the platform.\n" +
    "- Enquiry / Lead Commission: For every verified prospective student enquiry or direct admission lead generated by EduBird for " + orgName + ", a flat marketing facilitation fee of ₹" + enqComm + " shall be credited to EduBird.\n" +
    "- Payment Reconciliation: EduBird will disburse net tuition fees collected to the Institution's registered bank account on a bi-weekly settlement cycle (15th and 30th of every month) after deducting the agreed platform fee.\n\n" +
    "3. ACCREDITATION & COURSE ACCURACY\n" +
    "The Institution warrants that all course details, fees, curriculum, faculty credentials, and eligibility criteria submitted to EduBird are accurate, up-to-date, and compliant with statutory educational regulatory bodies (e.g., UGC, AICTE, State Boards).\n\n" +
    "4. STUDENT PROTECTION & ADMISSIONS COMPLIANCE\n" +
    "The Institution agrees to honor all confirmed admissions processed via EduBird and guarantee fair treatment, transparent refund handling, and adherence to advertised academic schedules.\n\n" +
    "5. TERM, RENEWAL & TERMINATION\n" +
    "This Agreement shall be valid for a period of 12 (Twelve) calendar months from the date of execution and shall automatically renew on mutually agreed commercial terms unless terminated by either party with a 30-day written notice.";

  const getDefaultStudentTerms = () => 
    "1. ACADEMIC INTEGRITY & ATTENDANCE POLICY\n" +
    "Students enrolled in programs at " + orgName + " through EduBird must maintain minimum 75% attendance in lectures, practical sessions, and periodic evaluations to remain eligible for semester examinations and official certifications.\n\n" +
    "2. COURSE FEES & REFUND POLICY\n" +
    "- Application fees and platform service fees are non-refundable once admission processing begins.\n" +
    "- Tuition fee refunds are governed strictly by the Institution's statutory refund regulations and UGC guidelines upon written withdrawal requests.\n" +
    "- Installment schedules must be adhered to; delayed fee payments may lead to temporary suspension of learning portal access.\n\n" +
    "3. STUDENT CODE OF CONDUCT\n" +
    "Students must strictly avoid plagiarism, copyright infringement, disruptive classroom behavior, or unauthorized sharing of proprietary course materials provided by the institution or EduBird.\n\n" +
    "4. GRIEVANCE REDRESSAL\n" +
    "Any academic grievances, evaluation disputes, or schedule conflicts should be raised first to the designated Department Head or Academic Coordinator at " + orgName + ".";

  const getDefaultAffiliateTerms = (affPct: string, enqComm: string) => 
    "1. AFFILIATE ENROLLMENT & UNIQUE IDENTIFIER\n" +
    "Every registered Affiliate is assigned a unique Affiliate Referral Code (matching their verified 10-digit mobile number) and specialized referral links to recommend programs offered by " + orgName + " and EduBird.\n\n" +
    "2. COMMISSION STRUCTURE & REWARD RATES\n" +
    "- Course Enrollment Commission: Affiliates earn " + affPct + "% direct referral bonus on the net course fee paid by every student who enrolls using their affiliate referral link or mobile code.\n" +
    "- Qualified Enquiry Bonus: Active affiliates receive ₹" + enqComm + " for every genuine, verified student enquiry submitted that meets platform quality validation standards.\n\n" +
    "3. PAYOUT SCHEDULE & MINIMUM THRESHOLD\n" +
    "- Commissions are credited to the Affiliate's EduBird Wallet immediately upon admission confirmation.\n" +
    "- Direct Bank / UPI withdrawals can be requested once the accumulated wallet balance reaches the minimum threshold of ₹500.\n\n" +
    "4. ETHICAL PROMOTION GUIDELINES\n" +
    "Affiliates must represent courses accurately and are strictly prohibited from making false claims, sending unsolicited spam, or engaging in deceptive promotional activities.";

  // Load existing agreement terms from backend
  useEffect(() => {
    if (!open || !institution?.id) return;

    let isMounted = true;
    setLoading(true);

    fetch("/api/admin/institutions/agreements?institutionId=" + institution.id)
      .then((res) => res.json())
      .then((data) => {
        if (!isMounted) return;
        if (data && data.data) {
          const row = data.data;
          const sPct = row.platform_sale_percentage ? String(row.platform_sale_percentage) : "10.00";
          const eComm = row.enquiry_commission ? String(row.enquiry_commission) : "50.00";
          const aPct = row.affiliate_commission_percentage ? String(row.affiliate_commission_percentage) : "10.00";

          setPlatformSalePercentage(sPct);
          setEnquiryCommission(eComm);
          setAffiliateCommissionPercentage(aPct);

          setOrgTerms(row.org_agreement_terms || getDefaultOrgTerms(sPct, eComm));
          setStudentTerms(row.student_terms || getDefaultStudentTerms());
          setAffiliateTerms(row.affiliate_terms || getDefaultAffiliateTerms(aPct, eComm));
        } else {
          // Defaults
          setPlatformSalePercentage("10.00");
          setEnquiryCommission("50.00");
          setAffiliateCommissionPercentage("10.00");
          setOrgTerms(getDefaultOrgTerms("10.00", "50.00"));
          setStudentTerms(getDefaultStudentTerms());
          setAffiliateTerms(getDefaultAffiliateTerms("10.00", "50.00"));
        }
      })
      .catch((err) => {
        console.error("Failed to load agreement:", err);
        // Fallback to defaults
        setOrgTerms(getDefaultOrgTerms("10.00", "50.00"));
        setStudentTerms(getDefaultStudentTerms());
        setAffiliateTerms(getDefaultAffiliateTerms("10.00", "50.00"));
      })
      .finally(() => {
        if (isMounted) setLoading(false);
      });

    return () => {
      isMounted = false;
    };
  }, [open, institution?.id, orgName]);

  const handleSaveAgreement = async () => {
    if (!institution?.id) return;
    setSaving(true);

    try {
      const res = await fetch("/api/admin/institutions/agreements", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          institutionId: institution.id,
          platformSalePercentage: parseFloat(platformSalePercentage) || 10,
          enquiryCommission: parseFloat(enquiryCommission) || 50,
          affiliateCommissionPercentage: parseFloat(affiliateCommissionPercentage) || 10,
          orgAgreementTerms: orgTerms,
          studentTerms: studentTerms,
          affiliateTerms: affiliateTerms,
        }),
      });

      const json = await res.json();
      if (!res.ok) {
        throw new Error(json.error || "Failed to save agreement terms");
      }

      toast.success("Agreement terms & commission rates saved successfully!");
      setIsEditing(false);
    } catch (err: any) {
      toast.error(err.message || "Failed to save agreement");
    } finally {
      setSaving(false);
    }
  };

  const handleResetDefaults = () => {
    setOrgTerms(getDefaultOrgTerms(platformSalePercentage, enquiryCommission));
    setStudentTerms(getDefaultStudentTerms());
    setAffiliateTerms(getDefaultAffiliateTerms(affiliateCommissionPercentage, enquiryCommission));
    toast.info("Reset to standard EduBird legal templates.");
  };

  const handlePrint = () => {
    window.print();
  };

  const handleCopyText = (text: string, tabName: string) => {
    navigator.clipboard.writeText(text);
    setCopiedTab(tabName);
    toast.success(tabName + " agreement copied to clipboard");
    setTimeout(() => setCopiedTab(null), 2500);
  };

  if (!institution) return null;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="!w-[96vw] sm:!w-[95vw] !max-w-6xl sm:!max-w-6xl md:!max-w-6xl lg:!max-w-6xl xl:!max-w-6xl h-[92vh] max-h-[92vh] !p-0 flex flex-col overflow-hidden rounded-2xl border-slate-200 dark:border-neutral-800 shadow-2xl bg-white dark:bg-neutral-950 [&>button]:text-white [&>button]:hover:bg-white/20 [&>button]:top-5 [&>button]:right-5">
        <DialogHeader className="sr-only">
          <DialogTitle>Institution Agreement & Commercials - {orgName}</DialogTitle>
          <DialogDescription>EduBird Platform Partnership Terms, Commission Rates, and Memorandums</DialogDescription>
        </DialogHeader>

        {/* TOP BANNER / HEADER */}
        <div className="bg-gradient-to-r from-slate-900 via-indigo-950 to-slate-900 text-white p-5 md:p-6 shrink-0 border-b border-white/10 relative">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div className="space-y-1.5">
              <div className="flex items-center gap-2.5 flex-wrap">
                <Badge className="bg-indigo-500/20 text-indigo-300 border-indigo-500/30 text-xs font-semibold px-2.5 py-0.5">
                  <ShieldCheck className="w-3.5 h-3.5 mr-1 text-indigo-400 inline" />
                  Official Legal Agreement
                </Badge>
                <span className="text-xs text-slate-400 font-mono">Ref: {agreementRef}</span>
                <span className="text-xs text-slate-400">• Effective: {agreementDate}</span>
              </div>
              <h2 className="text-xl md:text-2xl font-bold tracking-tight text-white flex items-center gap-2">
                <FileCheck2 className="w-6 h-6 text-indigo-400 shrink-0" />
                Agreement Documents & Commercial Terms
              </h2>
              <p className="text-xs md:text-sm text-slate-300">
                Partner: <strong className="text-white">{orgName}</strong> ({orgType}) • Location: {orgCity}
              </p>
            </div>

            {/* ACTION CONTROLS */}
            <div className="flex items-center gap-2 flex-wrap self-end md:self-auto">
              <Button
                variant="outline"
                size="sm"
                onClick={() => setIsEditing(!isEditing)}
                className="bg-white/10 hover:bg-white/20 text-white border-white/20 text-xs font-medium h-9"
              >
                {isEditing ? (
                  <>
                    <Eye className="w-3.5 h-3.5 mr-1.5 text-cyan-400" />
                    Preview Mode
                  </>
                ) : (
                  <>
                    <Edit3 className="w-3.5 h-3.5 mr-1.5 text-amber-400" />
                    Edit Terms & Rates
                  </>
                )}
              </Button>

              {isEditing && (
                <Button
                  variant="outline"
                  size="sm"
                  onClick={handleResetDefaults}
                  className="bg-white/10 hover:bg-white/20 text-white border-white/20 text-xs font-medium h-9"
                  title="Reset to standard clauses"
                >
                  <RotateCcw className="w-3.5 h-3.5 mr-1.5" />
                  Reset Defaults
                </Button>
              )}

              <Button
                size="sm"
                onClick={handleSaveAgreement}
                disabled={saving || loading}
                className="bg-emerald-600 hover:bg-emerald-700 text-white font-medium text-xs h-9 shadow-lg shadow-emerald-900/30"
              >
                {saving ? (
                  <>
                    <Loader2 className="w-3.5 h-3.5 mr-1.5 animate-spin" />
                    Saving...
                  </>
                ) : (
                  <>
                    <Save className="w-3.5 h-3.5 mr-1.5" />
                    Save Agreement
                  </>
                )}
              </Button>

              <Button
                variant="outline"
                size="sm"
                onClick={handlePrint}
                className="bg-white/10 hover:bg-white/20 text-white border-white/20 text-xs font-medium h-9"
              >
                <Printer className="w-3.5 h-3.5 mr-1.5" />
                Print / Save PDF
              </Button>
            </div>
          </div>
        </div>

        {/* PLATFORM ADMIN COMMERCIAL RATES CONFIGURATION BAR */}
        <div className="bg-slate-100 dark:bg-neutral-900/90 border-b border-slate-200 dark:border-neutral-800 px-6 py-3.5 shrink-0">
          <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-3">
            <div className="flex items-center gap-2">
              <Sliders className="w-4 h-4 text-indigo-600 dark:text-indigo-400 shrink-0" />
              <div>
                <span className="text-xs font-bold uppercase tracking-wider text-slate-700 dark:text-slate-300">
                  Platform Admin Commercial Controls
                </span>
                <p className="text-[11px] text-slate-500 dark:text-slate-400">
                  Configure EduBird platform revenue share % on sales and enquiry commissions.
                </p>
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              {/* PLATFORM % ON SALE */}
              <div className="flex items-center gap-2 bg-white dark:bg-neutral-950 p-2 rounded-lg border border-slate-200 dark:border-neutral-800 shadow-sm">
                <div className="w-8 h-8 rounded-md bg-indigo-50 dark:bg-indigo-950/50 flex items-center justify-center shrink-0">
                  <Percent className="w-4 h-4 text-indigo-600 dark:text-indigo-400" />
                </div>
                <div className="flex-1 min-w-0">
                  <Label className="text-[10px] font-semibold text-slate-500 uppercase tracking-wider block truncate">
                    Platform Share on Sale
                  </Label>
                  <div className="flex items-center gap-1 mt-0.5">
                    <Input
                      type="number"
                      step="0.5"
                      min="0"
                      max="100"
                      disabled={!isEditing}
                      value={platformSalePercentage}
                      onChange={(e) => setPlatformSalePercentage(e.target.value)}
                      className="h-6 text-xs font-bold text-slate-900 dark:text-white px-1.5 py-0 w-16"
                    />
                    <span className="text-xs font-semibold text-slate-600 dark:text-slate-400">%</span>
                  </div>
                </div>
              </div>

              {/* ENQUIRY COMMISSION */}
              <div className="flex items-center gap-2 bg-white dark:bg-neutral-950 p-2 rounded-lg border border-slate-200 dark:border-neutral-800 shadow-sm">
                <div className="w-8 h-8 rounded-md bg-emerald-50 dark:bg-emerald-950/50 flex items-center justify-center shrink-0">
                  <IndianRupee className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
                </div>
                <div className="flex-1 min-w-0">
                  <Label className="text-[10px] font-semibold text-slate-500 uppercase tracking-wider block truncate">
                    Commission per Enquiry
                  </Label>
                  <div className="flex items-center gap-1 mt-0.5">
                    <span className="text-xs font-bold text-slate-600 dark:text-slate-400">₹</span>
                    <Input
                      type="number"
                      step="5"
                      min="0"
                      disabled={!isEditing}
                      value={enquiryCommission}
                      onChange={(e) => setEnquiryCommission(e.target.value)}
                      className="h-6 text-xs font-bold text-slate-900 dark:text-white px-1.5 py-0 w-20"
                    />
                  </div>
                </div>
              </div>

              {/* AFFILIATE REFERRAL % */}
              <div className="flex items-center gap-2 bg-white dark:bg-neutral-950 p-2 rounded-lg border border-slate-200 dark:border-neutral-800 shadow-sm">
                <div className="w-8 h-8 rounded-md bg-amber-50 dark:bg-amber-950/50 flex items-center justify-center shrink-0">
                  <Users className="w-4 h-4 text-amber-600 dark:text-amber-400" />
                </div>
                <div className="flex-1 min-w-0">
                  <Label className="text-[10px] font-semibold text-slate-500 uppercase tracking-wider block truncate">
                    Affiliate Referral Share
                  </Label>
                  <div className="flex items-center gap-1 mt-0.5">
                    <Input
                      type="number"
                      step="0.5"
                      min="0"
                      max="100"
                      disabled={!isEditing}
                      value={affiliateCommissionPercentage}
                      onChange={(e) => setAffiliateCommissionPercentage(e.target.value)}
                      className="h-6 text-xs font-bold text-slate-900 dark:text-white px-1.5 py-0 w-16"
                    />
                    <span className="text-xs font-semibold text-slate-600 dark:text-slate-400">%</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* BODY TABS & CONTENT AREA */}
        <div className="flex-1 overflow-y-auto p-4 md:p-6 bg-slate-50/50 dark:bg-neutral-900/50">
          {loading ? (
            <div className="flex flex-col items-center justify-center h-64 gap-3">
              <Loader2 className="w-8 h-8 animate-spin text-indigo-600" />
              <p className="text-sm text-slate-500">Loading agreement configuration...</p>
            </div>
          ) : (
            <Tabs
              value={activeTab}
              onValueChange={setActiveTab}
              className="w-full h-full flex flex-col"
            >
              <div className="flex items-center justify-between gap-4 mb-4 shrink-0 flex-wrap">
                <TabsList className="grid grid-cols-3 w-full max-w-2xl bg-slate-200 dark:bg-neutral-800 p-1 rounded-xl">
                  <TabsTrigger
                    value="edubird-org"
                    className="flex items-center justify-center gap-2 text-xs md:text-sm font-semibold rounded-lg data-[state=active]:bg-white dark:data-[state=active]:bg-neutral-950 data-[state=active]:shadow-sm py-2"
                  >
                    <Building2 className="w-4 h-4 text-indigo-600 dark:text-indigo-400 shrink-0" />
                    <span className="truncate">1. EduBird & {orgName}</span>
                  </TabsTrigger>
                  <TabsTrigger
                    value="for-students"
                    className="flex items-center justify-center gap-2 text-xs md:text-sm font-semibold rounded-lg data-[state=active]:bg-white dark:data-[state=active]:bg-neutral-950 data-[state=active]:shadow-sm py-2"
                  >
                    <GraduationCap className="w-4 h-4 text-emerald-600 dark:text-emerald-400 shrink-0" />
                    <span className="truncate">2. For Students</span>
                  </TabsTrigger>
                  <TabsTrigger
                    value="for-affiliates"
                    className="flex items-center justify-center gap-2 text-xs md:text-sm font-semibold rounded-lg data-[state=active]:bg-white dark:data-[state=active]:bg-neutral-950 data-[state=active]:shadow-sm py-2"
                  >
                    <Share2 className="w-4 h-4 text-amber-600 dark:text-amber-400 shrink-0" />
                    <span className="truncate">3. For Affiliates</span>
                  </TabsTrigger>
                </TabsList>

                <div className="flex items-center gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => {
                      const textToCopy =
                        activeTab === "edubird-org"
                          ? orgTerms
                          : activeTab === "for-students"
                          ? studentTerms
                          : affiliateTerms;
                      handleCopyText(textToCopy, activeTab);
                    }}
                    className="h-8 text-xs font-medium border-slate-300 dark:border-neutral-700 bg-white dark:bg-neutral-900"
                  >
                    {copiedTab === activeTab ? (
                      <>
                        <Check className="w-3.5 h-3.5 mr-1 text-emerald-600" />
                        Copied
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5 mr-1 text-slate-500" />
                        Copy Tab Terms
                      </>
                    )}
                  </Button>
                </div>
              </div>

              {/* TAB 1: BETWEEN EDUBIRD & ORG */}
              <TabsContent value="edubird-org" className="mt-0 space-y-4 focus-visible:outline-none">
                <div className="bg-white dark:bg-neutral-950 rounded-xl p-6 border border-slate-200 dark:border-neutral-800 shadow-sm space-y-6">
                  {/* TITLE CARD */}
                  <div className="text-center pb-4 border-b border-slate-200 dark:border-neutral-800">
                    <Badge className="bg-indigo-100 text-indigo-800 dark:bg-indigo-950/80 dark:text-indigo-300 mb-2">
                      Memorandum of Understanding (MOU) & Service Level Agreement
                    </Badge>
                    <h3 className="text-xl md:text-2xl font-bold text-slate-900 dark:text-white">
                      MASTER PLATFORM PARTNERSHIP AGREEMENT
                    </h3>
                    <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
                      Between <strong className="text-slate-800 dark:text-slate-200">EduBird Learning Technologies Pvt Ltd</strong> and{" "}
                      <strong className="text-slate-800 dark:text-slate-200">{orgName}</strong>
                    </p>
                  </div>

                  {/* PARTIES INFO BOX */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs bg-slate-50 dark:bg-neutral-900/80 p-4 rounded-xl border border-slate-200 dark:border-neutral-800">
                    <div className="space-y-1">
                      <span className="font-bold text-indigo-700 dark:text-indigo-400 uppercase tracking-wider text-[11px]">
                        First Party (Platform Provider)
                      </span>
                      <p className="font-semibold text-slate-900 dark:text-white">EduBird Learning Technologies Pvt. Ltd.</p>
                      <p className="text-slate-600 dark:text-slate-400">Headquarters: Tech Innovation Hub, Cyber City</p>
                      <p className="text-slate-600 dark:text-slate-400">Email: legal@edubird.io • Phone: +91 1800-EDUBIRD</p>
                    </div>
                    <div className="space-y-1">
                      <span className="font-bold text-emerald-700 dark:text-emerald-400 uppercase tracking-wider text-[11px]">
                        Second Party (Partner Institution)
                      </span>
                      <p className="font-semibold text-slate-900 dark:text-white">{orgName}</p>
                      <p className="text-slate-600 dark:text-slate-400">Type: {orgType} • City: {orgCity}</p>
                      <p className="text-slate-600 dark:text-slate-400">Email: {orgEmail} • Phone: {orgPhone}</p>
                    </div>
                  </div>

                  {/* ACTIVE COMMERCIAL RATES SUMMARY PILLS */}
                  <div className="bg-gradient-to-r from-indigo-50/80 via-purple-50/80 to-slate-50 dark:from-indigo-950/40 dark:via-purple-950/20 dark:to-neutral-900 p-4 rounded-xl border border-indigo-100 dark:border-indigo-900/50">
                    <div className="text-xs font-bold text-indigo-950 dark:text-indigo-300 mb-2 flex items-center gap-1.5">
                      <Sparkles className="w-4 h-4 text-indigo-600 dark:text-indigo-400" />
                      Active Commercial Terms in Effect for this Institution:
                    </div>
                    <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
                      <div className="bg-white dark:bg-neutral-950 p-2.5 rounded-lg border border-indigo-100 dark:border-indigo-900 shadow-sm">
                        <span className="text-slate-500 text-[11px] block">EduBird Sale Revenue Share:</span>
                        <strong className="text-indigo-600 dark:text-indigo-400 text-sm font-bold">
                          {platformSalePercentage}%
                        </strong>{" "}
                        <span className="text-slate-500 text-[10px]">on every student fee</span>
                      </div>
                      <div className="bg-white dark:bg-neutral-950 p-2.5 rounded-lg border border-indigo-100 dark:border-indigo-900 shadow-sm">
                        <span className="text-slate-500 text-[11px] block">Enquiry / Lead Fee:</span>
                        <strong className="text-emerald-600 dark:text-emerald-400 text-sm font-bold">
                          ₹{enquiryCommission}
                        </strong>{" "}
                        <span className="text-slate-500 text-[10px]">per verified enquiry</span>
                      </div>
                      <div className="bg-white dark:bg-neutral-950 p-2.5 rounded-lg border border-indigo-100 dark:border-indigo-900 shadow-sm">
                        <span className="text-slate-500 text-[11px] block">Affiliate Bonus Payout:</span>
                        <strong className="text-amber-600 dark:text-amber-400 text-sm font-bold">
                          {affiliateCommissionPercentage}%
                        </strong>{" "}
                        <span className="text-slate-500 text-[10px]">on student admission</span>
                      </div>
                    </div>
                  </div>

                  {/* CLAUSES / TERMS TEXT */}
                  <div className="space-y-3">
                    <div className="flex items-center justify-between">
                      <h4 className="text-sm font-bold text-slate-800 dark:text-slate-200 uppercase tracking-wider flex items-center gap-2">
                        <Scale className="w-4 h-4 text-indigo-600" />
                        Agreement Clauses & Legal Terms
                      </h4>
                      {isEditing && (
                        <span className="text-[11px] text-amber-600 dark:text-amber-400 font-medium bg-amber-50 dark:bg-amber-950/50 px-2 py-0.5 rounded border border-amber-200 dark:border-amber-800">
                          Editing Mode Active — Click "Save Agreement" when done
                        </span>
                      )}
                    </div>

                    {isEditing ? (
                      <div className="space-y-2">
                        <Textarea
                          rows={14}
                          value={orgTerms}
                          onChange={(e) => setOrgTerms(e.target.value)}
                          className="font-mono text-xs leading-relaxed p-4 bg-slate-50 dark:bg-neutral-900 border-slate-300 dark:border-neutral-700"
                          placeholder="Write custom terms and clauses for EduBird & Organization agreement..."
                        />
                        <p className="text-[11px] text-slate-500">
                          Tip: You can modify standard clauses, change settlement cycles, add special conditions, or update payment terms.
                        </p>
                      </div>
                    ) : (
                      <div className="prose prose-sm dark:prose-invert max-w-none text-slate-700 dark:text-slate-300 text-xs leading-relaxed whitespace-pre-line bg-slate-50 dark:bg-neutral-900/60 p-5 rounded-xl border border-slate-200 dark:border-neutral-800 font-sans">
                        {orgTerms}
                      </div>
                    )}
                  </div>

                  {/* SIGNATURE / STAMP SECTION */}
                  <div className="pt-6 border-t border-slate-200 dark:border-neutral-800 grid grid-cols-1 sm:grid-cols-2 gap-8 text-xs">
                    <div className="border border-dashed border-slate-300 dark:border-neutral-700 p-4 rounded-xl bg-slate-50/50 dark:bg-neutral-900/40 text-center space-y-2">
                      <div className="h-12 flex items-center justify-center">
                        <span className="font-serif italic text-lg text-indigo-700 dark:text-indigo-400 font-semibold tracking-wide">
                          EduBird Digital Seal
                        </span>
                      </div>
                      <div className="border-t border-slate-300 dark:border-neutral-700 pt-2">
                        <p className="font-bold text-slate-900 dark:text-white">Authorized Signatory</p>
                        <p className="text-[11px] text-slate-500">EduBird Platform Legal & Compliance Dept.</p>
                      </div>
                    </div>

                    <div className="border border-dashed border-slate-300 dark:border-neutral-700 p-4 rounded-xl bg-slate-50/50 dark:bg-neutral-900/40 text-center space-y-2">
                      <div className="h-12 flex items-center justify-center">
                        <span className="font-serif italic text-lg text-emerald-700 dark:text-emerald-400 font-semibold tracking-wide">
                          {orgName}
                        </span>
                      </div>
                      <div className="border-t border-slate-300 dark:border-neutral-700 pt-2">
                        <p className="font-bold text-slate-900 dark:text-white">Dean / Principal / Director</p>
                        <p className="text-[11px] text-slate-500">{orgName} Administration</p>
                      </div>
                    </div>
                  </div>
                </div>
              </TabsContent>

              {/* TAB 2: FOR STUDENTS */}
              <TabsContent value="for-students" className="mt-0 space-y-4 focus-visible:outline-none">
                <div className="bg-white dark:bg-neutral-950 rounded-xl p-6 border border-slate-200 dark:border-neutral-800 shadow-sm space-y-6">
                  {/* TITLE CARD */}
                  <div className="text-center pb-4 border-b border-slate-200 dark:border-neutral-800">
                    <Badge className="bg-emerald-100 text-emerald-800 dark:bg-emerald-950/80 dark:text-emerald-300 mb-2">
                      Student Enrollment Terms & Code of Conduct
                    </Badge>
                    <h3 className="text-xl md:text-2xl font-bold text-slate-900 dark:text-white">
                      STUDENT ACADEMIC & ADMISSION AGREEMENT
                    </h3>
                    <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
                      Applicable to all students admitted to <strong className="text-slate-800 dark:text-slate-200">{orgName}</strong> via EduBird Platform
                    </p>
                  </div>

                  {/* SUMMARY INFO */}
                  <div className="bg-emerald-50/70 dark:bg-emerald-950/30 p-4 rounded-xl border border-emerald-100 dark:border-emerald-900/40 flex items-start gap-3 text-xs">
                    <AlertCircle className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
                    <div>
                      <strong className="text-emerald-900 dark:text-emerald-300 font-semibold block mb-0.5">
                        Mandatory Student Acceptance
                      </strong>
                      <p className="text-emerald-800 dark:text-emerald-400/90 leading-relaxed">
                        These terms are presented to students and parents during online application submission and enrollment fee payment.
                        Institution administrators can customize admission rules, attendance criteria, and exam eligibility clauses below.
                      </p>
                    </div>
                  </div>

                  {/* CLAUSES / TERMS TEXT */}
                  <div className="space-y-3">
                    <div className="flex items-center justify-between">
                      <h4 className="text-sm font-bold text-slate-800 dark:text-slate-200 uppercase tracking-wider flex items-center gap-2">
                        <GraduationCap className="w-4 h-4 text-emerald-600" />
                        Student Academic Terms & Clauses
                      </h4>
                      {isEditing && (
                        <span className="text-[11px] text-amber-600 dark:text-amber-400 font-medium bg-amber-50 dark:bg-amber-950/50 px-2 py-0.5 rounded border border-amber-200 dark:border-amber-800">
                          Editing Student Terms
                        </span>
                      )}
                    </div>

                    {isEditing ? (
                      <div className="space-y-2">
                        <Textarea
                          rows={14}
                          value={studentTerms}
                          onChange={(e) => setStudentTerms(e.target.value)}
                          className="font-mono text-xs leading-relaxed p-4 bg-slate-50 dark:bg-neutral-900 border-slate-300 dark:border-neutral-700"
                          placeholder="Write custom student enrollment terms and clauses..."
                        />
                      </div>
                    ) : (
                      <div className="prose prose-sm dark:prose-invert max-w-none text-slate-700 dark:text-slate-300 text-xs leading-relaxed whitespace-pre-line bg-slate-50 dark:bg-neutral-900/60 p-5 rounded-xl border border-slate-200 dark:border-neutral-800 font-sans">
                        {studentTerms}
                      </div>
                    )}
                  </div>
                </div>
              </TabsContent>

              {/* TAB 3: FOR AFFILIATES */}
              <TabsContent value="for-affiliates" className="mt-0 space-y-4 focus-visible:outline-none">
                <div className="bg-white dark:bg-neutral-950 rounded-xl p-6 border border-slate-200 dark:border-neutral-800 shadow-sm space-y-6">
                  {/* TITLE CARD */}
                  <div className="text-center pb-4 border-b border-slate-200 dark:border-neutral-800">
                    <Badge className="bg-amber-100 text-amber-800 dark:bg-amber-950/80 dark:text-amber-300 mb-2">
                      EduBird Partner Referral & Affiliate Guidelines
                    </Badge>
                    <h3 className="text-xl md:text-2xl font-bold text-slate-900 dark:text-white">
                      AFFILIATE REFERRAL & COMMISSION AGREEMENT
                    </h3>
                    <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
                      Governing all registered promoters, alumni, counselors, and student ambassadors referring courses for <strong className="text-slate-800 dark:text-slate-200">{orgName}</strong>
                    </p>
                  </div>

                  {/* AFFILIATE COMMISSIONS INFO BANNER */}
                  <div className="bg-amber-50/70 dark:bg-amber-950/30 p-4 rounded-xl border border-amber-100 dark:border-amber-900/40 flex items-start gap-3 text-xs">
                    <Award className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
                    <div>
                      <strong className="text-amber-900 dark:text-amber-300 font-semibold block mb-0.5">
                        Automated Tracking via Mobile Affiliate Code
                      </strong>
                      <p className="text-amber-800 dark:text-amber-400/90 leading-relaxed">
                        Every partner & affiliate uses their verified 10-digit mobile number as their universal referral code.
                        Current payout rate for this institution: <strong className="text-amber-950 dark:text-amber-200 font-bold">{affiliateCommissionPercentage}%</strong> per student admission and <strong className="text-amber-950 dark:text-amber-200 font-bold">₹{enquiryCommission}</strong> per verified enquiry.
                      </p>
                    </div>
                  </div>

                  {/* CLAUSES / TERMS TEXT */}
                  <div className="space-y-3">
                    <div className="flex items-center justify-between">
                      <h4 className="text-sm font-bold text-slate-800 dark:text-slate-200 uppercase tracking-wider flex items-center gap-2">
                        <Share2 className="w-4 h-4 text-amber-600" />
                        Affiliate Terms & Referral Clauses
                      </h4>
                      {isEditing && (
                        <span className="text-[11px] text-amber-600 dark:text-amber-400 font-medium bg-amber-50 dark:bg-amber-950/50 px-2 py-0.5 rounded border border-amber-200 dark:border-amber-800">
                          Editing Affiliate Terms
                        </span>
                      )}
                    </div>

                    {isEditing ? (
                      <div className="space-y-2">
                        <Textarea
                          rows={14}
                          value={affiliateTerms}
                          onChange={(e) => setAffiliateTerms(e.target.value)}
                          className="font-mono text-xs leading-relaxed p-4 bg-slate-50 dark:bg-neutral-900 border-slate-300 dark:border-neutral-700"
                          placeholder="Write custom affiliate referral terms and clauses..."
                        />
                      </div>
                    ) : (
                      <div className="prose prose-sm dark:prose-invert max-w-none text-slate-700 dark:text-slate-300 text-xs leading-relaxed whitespace-pre-line bg-slate-50 dark:bg-neutral-900/60 p-5 rounded-xl border border-slate-200 dark:border-neutral-800 font-sans">
                        {affiliateTerms}
                      </div>
                    )}
                  </div>
                </div>
              </TabsContent>
            </Tabs>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
