import { NextResponse } from "next/server";

import { getAuthenticatedUser } from "@/lib/auth/auth";
import { hasPermission } from "@/lib/auth/permissions";
import { resolveStudentEnrollmentContext } from "@/lib/auth/student-enrollment-context";
import { db } from "@/lib/db/db";

function errorResponse(error: unknown) {
  const message = error instanceof Error ? error.message : "Unable to load student documents";
  const status = message === "Forbidden: Admin access required"
    ? 403
    : message === "Unauthorized" || message === "User not found"
      ? 401
      : 400;
  return NextResponse.json({ error: message }, { status });
}

export async function GET(req: Request) {
  try {
    const currentUser = await getAuthenticatedUser(req);
    const canView =
      hasPermission(currentUser, "student.myclassroom.idcard.view") ||
      hasPermission(currentUser, "parent.childclassroom.idcard.view");
    if (!canView) throw new Error("Forbidden: Admin access required");

    const enrollment = await resolveStudentEnrollmentContext(
      db,
      req,
      currentUser.id,
      currentUser.role_codes
    );

    if (!enrollment) {
      return NextResponse.json({ data: null });
    }

    const studentId = enrollment.student_id;
    const institutionId = enrollment.institution_id;

    // Ensure table column exists
    await db.query(`
      ALTER TABLE student_id_cards
        ADD COLUMN IF NOT EXISTS enrollment_id INTEGER REFERENCES student_enrollments(id) ON DELETE SET NULL
    `).catch(() => {});

    // 1. Fetch all student ID cards (generated by institution admin)
    const idCardsRes = await db.query(
      `
        SELECT
          card.id,
          card.title,
          'id_card' AS document_kind,
          'ID Card' AS category_name,
          'id-card' AS category_slug,
          card.image_url,
          card.pdf_url,
          card.rendered_html,
          card.canvas_width,
          card.canvas_height,
          card.version,
          card.status,
          card.enrollment_id,
          card.created_at,
          card.updated_at,
          institution.name AS institution_name,
          generator.full_name AS generated_by_name
        FROM student_id_cards card
        INNER JOIN institution_profiles institution ON institution.id = card.institution_id
        LEFT JOIN users generator ON generator.id = card.generated_by
        WHERE card.student_id = $1
          AND card.institution_id = $2
          AND COALESCE(card.is_deleted, FALSE) = FALSE
        ORDER BY 
          CASE WHEN card.enrollment_id = $3 THEN 0 ELSE 1 END,
          card.created_at DESC, 
          card.id DESC
      `,
      [studentId, institutionId, enrollment.id]
    );

    // 2. Fetch all generated documents from institution_generated_documents (TC, Result Cards, Character, Bonafide, Achievements, etc.)
    const genDocsRes = await db.query(
      `
        SELECT
          doc.id,
          doc.title,
          'generated_document' AS document_kind,
          COALESCE(cc.name, 
            CASE 
              WHEN doc.reference_type = 'student_achievement_certificate' THEN 'Achievement Certificate'
              WHEN doc.reference_type = 'student_result_card' THEN 'Result Card'
              WHEN doc.reference_type = 'student_tc' THEN 'Transfer Certificate (TC)'
              WHEN doc.reference_type = 'student_id_card' THEN 'ID Card'
              WHEN doc.reference_type = 'student_bonafide_certificate' THEN 'Bonafide Certificate'
              WHEN doc.reference_type = 'student_character_certificate' THEN 'Character Certificate'
              WHEN doc.reference_type = 'student_hall_ticket' THEN 'Hall Ticket'
              WHEN doc.reference_type = 'student_offer_letter' THEN 'Offer Letter'
              ELSE 'Generated Certificate'
            END
          ) AS category_name,
          COALESCE(cc.slug, doc.reference_type, 'document') AS category_slug,
          doc.image_url,
          doc.pdf_url,
          doc.rendered_html,
          doc.canvas_width,
          doc.canvas_height,
          doc.version,
          doc.status,
          doc.enrollment_id,
          doc.created_at,
          doc.updated_at,
          institution.name AS institution_name,
          generator.full_name AS generated_by_name
        FROM institution_generated_documents doc
        INNER JOIN institution_profiles institution ON institution.id = doc.institution_id
        LEFT JOIN card_categories cc ON cc.id = doc.card_category_id
        LEFT JOIN users generator ON generator.id = doc.generated_by
        WHERE doc.reference_id = $1
          AND (doc.reference_type LIKE 'student%' OR doc.reference_type = 'student')
          AND doc.institution_id = $2
          AND COALESCE(doc.is_deleted, FALSE) = FALSE
        ORDER BY 
          CASE WHEN doc.enrollment_id = $3 THEN 0 ELSE 1 END,
          doc.created_at DESC, 
          doc.id DESC
      `,
      [studentId, institutionId, enrollment.id]
    );

    // 3. Fetch all uploaded student documents (Aadhar, Birth certificate, Marksheets, etc. added by institution)
    const uploadedDocsRes = await db.query(
      `
        SELECT
          sd.id,
          'uploaded_document' AS document_kind,
          sd.document_type,
          sd.document_number,
          sd.file_url,
          sd.is_verified,
          sd.resource_type,
          sd.created_at,
          sd.updated_at,
          verifier.full_name AS verified_by_name
        FROM student_documents sd
        LEFT JOIN users verifier ON verifier.id = sd.verified_by
        WHERE sd.student_id = $1
          AND COALESCE(sd.is_deleted, FALSE) = FALSE
        ORDER BY sd.created_at DESC, sd.id DESC
      `,
      [studentId]
    );

    const idCards = idCardsRes.rows;
    const generatedDocs = genDocsRes.rows;
    const uploadedDocs = uploadedDocsRes.rows;

    // Primary ID Card for default / full canvas view
    const primaryIdCard = idCards.find((c: any) => c.enrollment_id === enrollment.id) || idCards[0] || null;

    return NextResponse.json({
      data: {
        ...(primaryIdCard || {}),
        primaryIdCard,
        idCards,
        generatedDocuments: generatedDocs,
        uploadedDocuments: uploadedDocs,
        enrollment: {
          id: enrollment.id,
          studentId: enrollment.student_id,
          institutionId: enrollment.institution_id,
          institutionName: primaryIdCard?.institution_name || enrollment.institution_name,
        }
      },
    });
  } catch (error) {
    return errorResponse(error);
  }
}
